### ISSUE TITLE
ICE - VV DNA sequence search ambiguous '*' character behavior

### ISSUE THREAD

**Issue by njhillson** [TeselaGen/openVectorEditor#188]
I am not sure what the app is doing when I use the '*' character in an ambiguous DNA sequence search. Is it messing with a regex?

**Comment by tnrich** [comment]
This will now not return any search results

**Comment by njhillson** [comment]
Something funky is still happening for DNA ambiguous. Try "tgg*c". I receive hits for things like "tggca" and "tggcc".

**Comment by tnrich** [comment]
Hmm good catch. That is strange I thought * was just getting stripped completely. That's the desired functionality right, to just ignore random characters like "*"

**Comment by njhillson** [comment]
Well, for DNA ambiguous, * is not valid, so correct behavior to tell user that * is not supported for DNA ambiguous, or just have no matches. For protein * is a stop codon literal match, so it is a bit different there...

**Comment by tnrich** [comment]
I've added a note to alert users that * will match any character (not just atgc) when doing an ambiguous dna search. I think that should be sufficient to clear up any confusion and it also allows ambiguous dna searches to match non-atgc chars which would otherwise be impossible to do. 


![image](https://user-images.githubusercontent.com/2730609/62081534-b4d6c500-b207-11e9-909f-d3b41d5a110a.png)
