### ISSUE TITLE
Alignments > Add pairwise alignment option to alignment tool

### ISSUE THREAD

**Issue by tnrich** [TeselaGen/openVectorEditor#273]
Right now our alignment tool only handles multiple-sequence-alignments, but we'll want to support multiple **pairwise** alignments.

We'll need to add that option to the alignment creation tool as well as the alignment visualization.

**Comment by tiffanydai** [comment]
**Initial view (upon upload of e.g. 4 files of pairwise alignments):**
- Track of annotations (features, etc.) above the reference sequence
- Track of the reference sequence's nucleotides (with no gaps)
- Minimap with 4 tracks, each representing a pairwise alignment
**Upon clicking a track in the minimap, the view will be:**
- Track of annotations, with e.g. amino acids stretching across gaps
- Track of the reference sequence's nucleotides (with gaps)
- Track of annotations for the second sequence
- Track of the second sequence's nucleotides
**Other notes:**
- Clicking on a track in the minimap will open an alignment view of that specific pairwise alignment
- _(existing feature)_ Dragging around a highlight bar on the minimap (e.g. to a red region that is a stretch of mismatches) will simultaneously drag around the view of the pairwise alignment's nucleotide sequences
- A stretch of mismatches can show up as a red region in the minimap with a red line for each mismatch, but a stretch of gaps can be downgraded to one red line rather than a whole red region
- Clickable list of the pairwise alignments next to the clickable minimap tracks of pairwise alignments
- Add BLAST for generating alignment data

**Comment by tnrich** [comment]
@hplahar we're ready to have you integrate with ICE.

Here a little gif of the new pairwise alignment view in action:

![untitled](https://user-images.githubusercontent.com/2730609/38277947-09fddf9e-374f-11e8-9605-871f165af112.gif)


@njhillson I think that interface is closer to what you were looking for. 

@hplahar here is the api for getting your own pairwise alignment in the editor: 
https://github.com/TeselaGen/openVectorEditor#integrating-your-own-alignment-data-only-necessary-if-not-using-the-built-in-alignment-creation-tool

**Comment by XimeMora** [comment]
Pairwise alignment is working nicely!
