### ISSUE TITLE
Genbank feature parsing messes up when a feature wraps the whole sequence

### ISSUE THREAD

**Issue by christopher-lamkin** [TeselaGen/openVectorEditor#292]
_From @craftjk on November 11, 2017 22:43_

To replicate, try loading this genbank file into the main app and into LIMS.  In the main app, the GFPuv feature wraps the whole sequence and in the LIMS app it's only one base pair long.

[genbank.zip](https://github.com/TeselaGen/lims/files/1464176/genbank.zip)

![screen shot 2017-11-11 at 4 36 09 pm](https://user-images.githubusercontent.com/4167907/32694188-29167e92-c6ff-11e7-8414-05f2ee6363ff.png)
![screen shot 2017-11-11 at 4 36 20 pm](https://user-images.githubusercontent.com/4167907/32694189-292d8326-c6ff-11e7-8853-40b53aac2472.png)

_Copied from original issue: TeselaGen/lims#321_

**Comment by tnrich** [comment]
@christopher-lamkin this is definitely due to the sequence being read as linear. Can you set up a hangout and we can fix this one together?

**Comment by tnrich** [comment]
Hey @mfero after looking into the genbank file, it looks like the genbank is incorrect: 

![image](https://user-images.githubusercontent.com/2730609/39682183-4d757e66-5163-11e8-9ead-967caff0ee5f.png)

As you can see above, the genbank says its size is 108 bps when in actuality there are only 103 bps total in the file. 

It's for this reason the parser is failing to give the correct response. I could change the functionality of the parser to truncate the features to the end instead of putting them on the 1st bp instead. Seems a bit like the case of junk in junk out though. 

Thoughts?

**Comment by tnrich** [comment]
Okay well I went ahead and made features whose ends "hang off" be truncated to the end of the sequence instead of to 1.
