### ISSUE TITLE
Add option to have partial digests

### ISSUE THREAD

**Issue by tnrich** [TeselaGen/openVectorEditor#319]
More info needed.

**Comment by hcdepaoli** [comment]
Hi Thomas, I mentioned this functionality as it might help people to check for the pattern given by only a partial digestion that may occur in different scenarios. I can think of situations like checking a vector sent by a user and then I'm having a faulty (old, short lived etc) restriction enzymes that won't digest entirely or even when doing my own cloning and indeed looking for a partial digest when cloning parts (instead of domesticating the vector first to have unique sites before cloning - which adds in time).

**Comment by hcdepaoli** [comment]
Hi Thomas,

Yes, this sounds pretty good.
No need to create " nothing cuts" as these are 1) hard to predict for
coiled/supercoiled DNA and 2)people run (or at least they should) a
non-digest control on their gels so a total failure can be tracked.

Thank you!!

Henrique

**Comment by tnrich** [comment]
@hcdepaoli I've added a first pass of this to the latest version of OVE --http://teselagen.github.io/openVectorEditor/#/Editor

I've added partial digest functionality and added max cutsite limits to regular and partial digests to prevent the browser from freezing. 

Want to check it out and let me know if it is working for you?

**Comment by hcdepaoli** [comment]
Hi Thomas,

Thanks for the implementation!
This is very helpful, will definitely use it!

Cheers,

Henrique

**Comment by tnrich** [comment]
Cheers @hcdepaoli , I'll close this for now! Don't hesitate to reach out if you encounter any issues with it :)
