### ISSUE TITLE
Expanding the preview area in pairwise alignment causes the dna letters to disappear

### ISSUE THREAD

**Issue by hplahar** [TeselaGen/openVectorEditor#332]
After clicking and dragging one of the boundaries of the yellow area to increase the view range of the pairwise alignment, the dna letters were no longer displayed. See the attached screenshot
<img width="811" alt="screen shot 2018-06-06 at 9 57 25 am" src="https://user-images.githubusercontent.com/1694026/41053559-c801ef8c-6970-11e8-81b3-a8597585825c.png">

**Comment by tnrich** [comment]
Hey @hplahar the bps are not being shown once the sequence has been zoomed out past a certain level. We have the threshold character width below which we don't show the individual dna bps. Currently that threshold is set to 7px. We could change that to make it smaller. 

Alternatively we could render say colored rectangles instead of actual letters after a certain threshold. 

Thoughts?

**Comment by hplahar** [comment]
Can both options be applied? i.e. make the threshold smaller and render rectangles beyond that.

**Comment by tnrich** [comment]
Yeah I'll try that out for the alignment view and let you know how it goes.

**Comment by XimeMora** [comment]
This looks good!
