### ISSUE TITLE
Get rid of empty white space at the bottom

### ISSUE THREAD

**Issue by tiffanydai** [TeselaGen/openVectorEditor#383]
feedback from @hplahar: 

![img_2632](https://user-images.githubusercontent.com/35508772/47322367-7f63d200-d60c-11e8-863b-7ef1069921fb.jpg)
Get rid of empty white space at the bottom of the screen (especially noticeable to JBEI users with big monitors)

@tnrich

**Comment by mfero** [comment]
@tiffanydai is this fixed by https://github.com/TeselaGen/hde/issues/2117

**Comment by tiffanydai** [comment]
@mfero kind of, the solution is probably the same, but I think it'll be implemented on @hplahar's end. I mentioned to Hector that he can probably fix it the same way that we fixed it in our app. Can you try setting the height of the editor to fit the window, Hector? 

![screen shot 2018-10-22 at 3 28 53 pm](https://user-images.githubusercontent.com/35508772/47323140-6dcff980-d60f-11e8-833b-de19f7385916.png)

**Comment by tnrich** [comment]
@hplahar please ignore what @tiffanydai says above. Instead you should pass: 
```js
createVectorEditor({
   isFullscreen: true
   //optional: 
   handleFullscreenClose: ()=>{do some logic here}
})
```

Note that I've published this change as a new major version because it will break existing functionality: passing `handleFullscreenClose` alone will no longer force the editor into fullscreen mode, you'll also need to add `isFullscreen` now.
