### ISSUE TITLE
Alignments > Minimap axis numbers don't match sequences axis numbers

### ISSUE THREAD

**Issue by XimeMora** [TeselaGen/openVectorEditor#388]
@tnrich
Minimap axis numbers don't match sequences axis numbers when scrolling horizontally 

![alignment axis](https://user-images.githubusercontent.com/21211903/47751241-77c8ac80-dc4e-11e8-86ee-acb16b6e1606.gif)

**Comment by tnrich** [comment]
Yikes good catch!

**Comment by tnrich** [comment]
Whoops scratch what I said above. 

This is intentional. As you can see, the sequences are indexed differently because they align to each other with gaps. 

Maybe this is too confusing, but the bottom axis numbering includes all gaps whereas the per-sequence axis numbering does not include gaps. 

I'm not sure if there is a better way of doing this but if anyone has ideas let me know. @tiffanydai

**Comment by tnrich** [comment]
Closing this for now unless someone has a better idea
