### ISSUE TITLE
VE > lines pointing to features/parts (from labels) should adjust when adding/deleting annotations

### ISSUE THREAD

**Issue by XimeMora** [TeselaGen/openVectorEditor#389]
@tnrich
When adding or deleting annotations in the plasmid map the label lines from annotations don't adjust their length accordingly and can be confusing:

![screen shot 2018-10-31 at 3 34 24 pm](https://user-images.githubusercontent.com/21211903/47822861-f8f17380-dd22-11e8-97e4-ab6cae6b1c89.png)

![screen shot 2018-10-31 at 3 37 09 pm](https://user-images.githubusercontent.com/21211903/47822867-fd1d9100-dd22-11e8-83cd-25a9b3ea384d.png)

![screen shot 2018-10-31 at 3 37 33 pm](https://user-images.githubusercontent.com/21211903/47822869-00b11800-dd23-11e8-911e-9cbcc03802f6.png)

**Comment by tnrich** [comment]
@XimeMora I can't reproduce this. Can you send a little video of this?

**Comment by XimeMora** [comment]
@tnrich what I meant here is that the lines pointing to features/parts from labels normally stop at the ring (axis) or they are almost touching it as you can see in the first image above, then adding parts is pushing the lines further away from the ring, sometimes pointing nowhere or sometimes many of them pointing to just one annotation, as in the last image, does it make sense?

**Comment by XimeMora** [comment]
@tnrich maybe it look cleaner and not confusing if the lines stop outside of the part radius I think.

**Comment by tnrich** [comment]
I think that this might be less confusing if we just draw the label lines all the way to their respective features: 

![image](https://user-images.githubusercontent.com/2730609/62488396-11daf980-b779-11e9-9291-f13ffd37fbd2.png)


Instead of truncating them like we do now.  

If we draw the non-hovered lines lightly enough I don't think they really get in the way of the overall visualization.

**Comment by XimeMora** [comment]
That seems like a good idea to me 👍
