### ISSUE TITLE
HDE > VE > Copy DNA selection > capitalization should persist

### ISSUE THREAD

**Issue by siobhandavis** [TeselaGen/openVectorEditor#468]
Copying (and pasting) a DNA selection to Excel, for example, should maintain capitalization.

**Comment by siobhandavis** [comment]
TG-201

**Comment by tnrich** [comment]
@siobhandavis I think sequence case when copying is preserved currently, it just doesn't factor in the "Upper Case" and "Lower Case" options. For example: 
![image](https://user-images.githubusercontent.com/2730609/57255968-415b5800-700a-11e9-9a82-9a6f6e1d58cf.png)
You can see above that the copied text retains its casing. But if I choose to upper-case everything: 
![image](https://user-images.githubusercontent.com/2730609/57256020-5df79000-700a-11e9-8b3e-0cf53ef8ba21.png)
Then that upper casing is not preserved when copying. I can make it so the sequence casing option is reflected in the copy, I just wanted to make sure that is what this ticket is asking for.

**Comment by tnrich** [comment]
Hmm.. after thinking it through a bit more, I think it might make more sense to get rid of the options to view the sequence case differently. I think if the user wants to view the case differently, they should be changing the underlying data so that the sequence will always be upper or lower. 

So instead of a view option to change sequence case, we'd get an option under edit like so: 
![image](https://user-images.githubusercontent.com/2730609/57256933-d9f2d780-700c-11e9-862f-059af64f2873.png)

@gmcarthuriv do you have any thoughts on this? Do you ever want a view-only change to the sequence case? 

Thanks!

**Comment by gmcarthuriv** [comment]
I agree, @tnrich - don't really need a view-only change. Thanks! 😎

**Comment by tnrich** [comment]
@gmcarthuriv one thing to note about changing our approach here is that it might make it slightly more complicated for you to **always** have you sequences being defaulted to upper case. In order to upper case your sequences you'll now have to Edit >  Change Case > Upper Case Sequence: 

![image](https://user-images.githubusercontent.com/2730609/57904511-e4d91380-7827-11e9-8ab5-42cdd1527e53.png)

**Comment by tnrich** [comment]
@gmcarthuriv one more thing to be aware of, by removing the "view-only" sequence case change, users won't be able to view the sequence in their preferred manner when the sequence is in read-only mode. Just something to be aware of. 

Maybe we should have both? I am not sure..

**Comment by gmcarthuriv** [comment]
@tnrich, sorry I missed this notification earlier. If this ends up being too gnarly I'll let you know - might be something that we need to revert. I'm looking forward to checking out the new behavior.

**Comment by tnrich** [comment]
This has been implemented so I'll close this issue for now. Let me know if there are issues with the new behavior :)
