### ISSUE TITLE
Updating OVE to use react-select v2

### ISSUE THREAD

**Issue by CathyC93** [TeselaGen/openVectorEditor#469]
@tnrich

Hi,
I work on a team with @ericsturman, and we are taking advantage of the custom right-click menu item on the Open Vector Editor.  We are using this to bring up a dialog that will include a select dropdown.  We are using material-ui in our app, so we were hoping to be able to use v2 of react-select.  Currently, we have v1 of react-select as a peer dependency in our app because OVE is using it, and we were wondering if it would be convenient for OVE to be updated to support v2 of react-select.  Please let me know if this a possibility, and thanks again for all your work on Open Vector Editor! 😄

Thanks,
Cathy

**Comment by tnrich** [comment]
Hi @CathyC93 I'll look into how hard making this change would be across our tools and get back to you.

**Comment by tnrich** [comment]
Hey @CathyC93 so I've been looking into switching over all of our selects to use blueprint's built in Select and MultiSelect components as this is something I think we'll want to do eventually to unify our component styling. If this were to happen, then that would fix your issue and you could use react-select v2 without any conflicting package names. 

Unfortunately, I've found that the performance of the blueprint select is not yet up to snuff:   https://github.com/palantir/blueprint/issues/1607

Because of that I plan on waiting to make this update. In the mean time, you could fork and re-publish react-select v2 and use it like that, or re-export it from a helper component module to avoid package.json naming conflicts. Let me know if that could work for you.

**Comment by tnrich** [comment]
Hey @CathyC93 you can update to the latest beta version of TRC and OVE `yarn add open-vector-editor@beta teselagen-react-components@beta` and they should be free of all references to react select. I've switched everything over to use the blueprint multi-select component.

Let me know if that works for you.

**Comment by tnrich** [comment]
Closing this because there is no longer a hard react select dep in OVE si you should be free to use whatever version of it you please.
