### ISSUE TITLE
Using beforeSequenceInsertOrDelete when selection crosses origin produces unexpected results

### ISSUE THREAD

**Issue by ericsturman** [TeselaGen/openVectorEditor#470]
@tnrich

We are using the `beforeSequenceInsertOrDelete` feature to show users sequence text they have changed during their session.  If we highlight the first 6 bases of the demo and replace with `aaaaaa` the result is a `CHANGED_SEQUENCE` part and our replaced text on the first 6 bases as expected.  But if our 6 base selection crosses the origin (in the middle of the selection) and we paste the same sequence, the part covers the last 3 bases of the sequence and the changed sequence is placed at the first 6 bases. 

* selection:
![Screen Shot 2019-05-10 at 7 54 49 AM](https://user-images.githubusercontent.com/4339551/57529738-41ee3a00-72fb-11e9-8f65-2388159c82cc.png)

* `CHANGED_SEQUENCE` part at end of sequence:
![Screen Shot 2019-05-10 at 7 55 26 AM](https://user-images.githubusercontent.com/4339551/57529813-72ce6f00-72fb-11e9-8695-945ddb039c98.png)

* pasted text at beginning of sequence:
![Screen Shot 2019-05-10 at 7 55 14 AM](https://user-images.githubusercontent.com/4339551/57529779-5df1db80-72fb-11e9-8eb7-4c1b719b2224.png)

**Comment by tnrich** [comment]
@ericsturman good catch! I'll take a look and see where this issue is arising from exactly. Something is definitely very off in the photos you sent me -- not only is the part not where you want it to be, the existing annotations themselves are being shifted around incorrectly it looks like. There must be something off with the insert sequence data code around the origin. 

I do know that inserting around the origin has some kind of tricky edge cases. 
In this case it seems obvious that a 1-1 replacement around the origin should do a clean replacement, but...
What if you're replacing a 6bp selection around the origin with 20 bps. Do 3 bps go on one side of the origin and then 17 bps at the start of the sequence? 
What if you're replacing a 20 bp selection around the origin (split 10-10) with only 8 bps. Do they all get put at the end of the sequence? 

I think the answer is yes in both of those cases but I could see users maybe expecting a different functionality. 

Another option would be to always insert at the start of any replacement which would mean that all bps would always be added to the start/end of the selection. That would fit more closely with the way that replacement is currently handled in the editor. Replacement right now always does a deletion action followed by an insertion action which is why all the bps are being added at the start of the sequence. 

The deletion -> insertion flow is definitely the easiest model to make work in the code, but maybe it isn't the most intuitive for biologists. Let me rope in @njhillson to see if he has any thoughts. I'd like to hear what you think as well @ericsturman . Thanks!

**Comment by ericsturman** [comment]
Thank you @tnrich !  I agree with your first set of scenarios as do other members of the team.

**Comment by tnrich** [comment]
@ericsturman so you're voting for this strategy: 
When replacing a 6bp selection around the origin with 20 bps, put 3 bps on one side of the origin and then 17 bps at the start of the sequence?
When replacing a 20 bp selection around the origin (split 10-10) with only 8 bps, put them all at the end of the sequence? 

Seems reasonable to me. 

Let me see what others on my team have to say.

**Comment by tnrich** [comment]
It appears benchling goes with the delete --> insert at end of selection strategy: 
![image](https://user-images.githubusercontent.com/2730609/57543912-a1a01180-730a-11e9-94e1-5d73fc2b342a.png)

Our teselagen legacy editor does the delete --> insert at start of selection strategy: 
![image](https://user-images.githubusercontent.com/2730609/57544844-6a7f2f80-730d-11e9-9de4-c190c32e0be3.png)

I'd like to know what snapgene and geneious do as well.

**Comment by tnrich** [comment]
Apparently geneious and snapgene both do the `delete --> insert at end of selection` strategy:

![image](https://user-images.githubusercontent.com/2730609/57549236-d797c280-7317-11e9-941d-35a03f799a92.png)


@ericsturman because it seems to be a reasonable strategy and the general convention in other tools, I am going to implement the `delete --> insert at end of selection` strategy. This will also be the strategy used for determining where the cursor should be placed when deleting around the origin (delete -> place cursor at start of sequence (this currently has issues))

I hope that is alright with you. You can always choose to rotate the sequence after a replacement to get your desired orientation.

**Comment by ericsturman** [comment]
@tnrich this will work fine for us.  Thanks again!

**Comment by tnrich** [comment]
@ericsturman can you please try v8.0.43 here: http://teselagen.github.io/openVectorEditor/#/Editor 

I've implemented the `delete --> insert at end of selection` strategy for REPLACE actions and `delete --> insert at start and wrap` for COMPLEMENT/REVCOMP actions. 

If you want you should also be able to choose your preferred strategy by altering the options returned in beforeSequenceInsertOrDelete:

```js
beforeSequenceInsertOrDelete: (
  sequenceDataToInsert,
  existingSequenceData,
  caretPositionOrRange,
  // the maintainOriginSplit option will be passed in as TRUE on complement/revComp actions (delete --> insert at start of selection and wrap around origin)
  // and FALSE on replace actions (delete --> insert at end of selection)
  options // {maintainOriginSplit: true} 
) => {
  return {
    // you can return one or more of the following to override the values used
    sequenceDataToInsert: myFilterSequenceDataToInsertFn(sequenceDataToInsert),
    existingSequenceData: myFilterExistingSeqFn(sequenceDataToInsert,caretPositionOrRange),
    caretPositionOrRange: myChangeCaretPosFn(caretPositionOrRange),
    options //you can pass {maintainOriginSplit: true} always if you want to always to wrap inserts around origin
  }
}
```js

Let me know if that works for you. 

As a side note, I've also updated the `Edit > Select...` dialog.

**Comment by ericsturman** [comment]
@tnrich Thank you for accommodating both scenarios.  We decided to go with the `{maintainOriginSplit: true}` and everything works fine except for the selection layer start being placed at the beginning of the vector sequence instead of the beginning of the newly inserted sequence.  The length of the selection is correct; it's only the start/end coordinates that are skewed.

**Comment by tnrich** [comment]
Hey @ericsturman glad it is _mostly_ working out for you :) 

I've added a branch (https://github.com/TeselaGen/openVectorEditor/tree/todoericsturman) for you with two todos in it (find them by doing a find all for the word `todoericsturman`) 


In that branch I've altered the signature of the wrappedInsertSequenceDataAtPositionOrRange function to return user defined options to allow for customizing how the selection layer is updated, but more work is needed to actually define that custom logic. Can you take a look at actually adding that custom logic where I've indicated with the todo notes as well as adding tests to the demo page that the user defined `maintainOrigin: true` selection/insertion logic works as expected? 

If so that would be greatly appreciated. Let me know if you have any questions. Cheers!

**Comment by tnrich** [comment]
This should be fixed by https://github.com/TeselaGen/openVectorEditor/pull/480

Let me know if you have any more issues with this @ericsturman. Great work!
