### ISSUE TITLE
Editor Handler for Selection Layer

### ISSUE THREAD

**Issue by hplahar** [TeselaGen/openVectorEditor#541]
@tnrich
Is there a handler available for listening to changes to the selection layer? I am looking for a way to get information about user selections as they happen.

**Comment by tnrich** [comment]
Hey @hplahar, I'm pretty sure I understand what you're asking for. I've added a `onSelectionOrCaretChanged` handler for you. You can see it in action at http://teselagen.github.io/openVectorEditor/#/Editor?onSelectionOrCaretChanged=true

Here's it's signature: 
```
onSelectionOrCaretChanged: ({ caretPosition, selectionLayer }) => {//your code here}
```
whenever this is called, either `caretPosition=-1` or `selectionLayer={start: -1, end: -1}` 

It might look a little strange that I've lumped together what could have been 2 separate handlers, onCaretChanged and onSelectionChanged. I did that because I found that onSelectionChanged wasn't being hit when onCaretChanged was called and vice versa. Combining them ensures we won't miss an update to either. 

Let me know if you need anything else.

**Comment by hplahar** [comment]
Thanks. That should meet my needs. I will give it a try and let you know
how it goes

**Comment by tnrich** [comment]
@hplahar  I'll close this. Please re-open if you have any issues. Also just out of curiosity, what do you need that handler for?

**Comment by hplahar** [comment]
@tnrich Working well so far. 
In DIVA, one of the primary ways users enter "parts" into the design is to go into openVE in ICE, select the subset of the sequence (or feature) and then copy and paste into device editor. I am enabling users to use openVE in deviceeditor to do this selection. So now they will be able to import a sequence, visualize it in openVE and by either clicking on the feature or dragging it, they can select the start and stop base pairs that indicate what part they are adding. Hope that makes sense. At some point I hope to be able to have the users do everything in openVE (just get the state when they are done) and not have to use the handlers.
