### ISSUE TITLE
Package version with UMD files only

### ISSUE THREAD

**Issue by MarcelBolten** [TeselaGen/openVectorEditor#672]
Hi Thomas (@tnrich),

In case there is a project that does not use React, the dependency load added by OVE is quite substantial if installed by e.g. `npm install open-vector-editor`.
Is there a possibility to provide a package with only the umd version of OVE e.g. 'open-vector-editor-umd'? This way one could easily profit from the latest version of OVE without loading all the dependencies that are not used.

Best,
Marcel

**Comment by tnrich** [comment]
Hey @MarcelBolten ! I like the idea of what you're suggesting but I am wondering about your use case. Are your users doing an npm install of your project locally? 

I am a little hesitant to split out another umd-only npm package because it will add to the build complexity but will do it if there is no other option. I'm wondering if you could pull it and cache it from unpkg (https://unpkg.com/browse/open-vector-editor@12.0.18/umd/open-vector-editor.min.js)  or another cdn. 

Unfortunately I'll be gone for the next month on vacation so won't be able to do anything on this until I get back. Let me know what you're thinking though. 

Cheers,
Thomas

**Comment by MarcelBolten** [comment]
Upfront, I'm not the main developer of [elabftw](https://github.com/elabftw/elabftw) where I want to [integrate OVE](https://github.com/elabftw/elabftw/pull/2255), the main developer is @NicolasCARPi.

eLabFTW is an electronic lab notebook manager for research teams. It is designed to be installed on a server, and people from the team can log in from their browser.

During setup on the server yarn is used to pull dependencies to build the JavaScript front-end bundels. In a first attempt, I added open-vector-editor as a dependency but because of all the follow-up dependencies that seems to be an overkill to 'just' get the umd version. It would be great to be able to pull the umd version in a way that allows for easy updates. Including it straight from the unpkg.com requires manually checking and updating OVE.
One solution is doing exactly this using grunt.js to pull it from registry.npmjs.org:
```javascript
...
shell: {
  ove: {
    // download open-vector-editor from Node package manager, extract only umd files and cleanup
    command: [
      'wget -q -O /tmp/OVE.tgz https://registry.npmjs.org/open-vector-editor/-/open-vector-editor-12.0.22.tgz',
      'tar -C web/app/ove/ -zxmf /tmp/OVE.tgz package/umd/ --strip-components 2 --overwrite',
      'rm /tmp/OVE.tgz'
    ].join('&&')
  }
}
```
However, I can understand that you are hesitant to split out another umd-only npm package because of the build complexity.

Hopefully you are not really unfortunate to go on vacation for a month 😉.
Happy to wait for your answer and thoughts.

Best,
Marcel

**Comment by NicolasCARPi** [comment]
Please note that I would be more than willing to sponsor work on this :moneybag: ;)

**Comment by MarcelBolten** [comment]
Hi Thomas @tnrich,
Do you have any updates for us?

**Comment by tnrich** [comment]
@MarcelBolten sorry this got lost in the shuffle for me. I'm still a little unsure about what the best solution for your use case would be. Basically you want another npm module that is just the UMD file? 

You say above that 
>Including it straight from the unpkg.com requires manually checking and updating OVE.

Did you know you can get an "always up to date" version of OVE by linking to the unpkg umd file without specifying a version number: https://unpkg.com/browse/open-vector-editor/umd/open-vector-editor.min.js

Would that do it for you? Or do you need a more custom solution. 

Cheers,
Thomas

**Comment by NicolasCARPi** [comment]
@tnrich but then if the version changes, the integrity shasum won't be correct anymore! Also, all the typescript/javascript is bundled with webpack from npm hosted modules. Having it in the package.json also helps with vulnerabilities scanning.

I believe the main issue is that the way it is currently packaged pulls too many dependencies, which makes maintainance a burden (with yarn.lock conflicts and such). A minimal version would be great to have.

**Comment by MarcelBolten** [comment]
Hi Thomas @tnrich,

Can you comment on how you would like to move on with our request for a minimal version of openVectorEditor?
I really would love to see openVectorEditor become a feature implemented in eLabFTW. I assume it will make life of many researches easier if they can have a quick look at their DNA/RNA/Protein sequences without the need to open additional software.

Cheers,
Marcel

**Comment by tnrich** [comment]
@MarcelBolten I've been thinking about this but am not quite sure how to proceed forward. Let me loop in some coworkers of mine who might have an idea of how to do what you're asking. 

Basically I haven't thought of a good way of publishing a UMD-only version of the package... 

In theory it is easy, just release a new package, open-vector-editor-umd, with only the umd file exported.. In practice this is a little tricky because npm packages can't have multiple package.json's. We'd probably have to do something kind of hacky, like right a script that modifies the package.json name and re-publishes the package and the reverts the package.json as part of the version script. That's all I can really think of.. 

I think this could also be handled on your end by creating and releasing an npm package that just pulls the ove-package as a dev-dep, pulls the umd file into a top level, and republishes it (this is kind of like the grunt script).

Am I missing an easy solution to this @tgreen7 or @tgadam?

**Comment by MarcelBolten** [comment]
Hi @tnrich,

@NicolasCARPi and I worked on a way to republish the umd files.

Repo: https://github.com/deltablot/ove-umd-builder
npm pkg: https://www.npmjs.com/package/@deltablot/open-vector-editor-umd

Thanks for encouraging us to republish your work.
Cheers,
Marcel

**Comment by tnrich** [comment]
@MarcelBolten awesome to hear you were able to set that up! Seems like it should work well. I bet with some effort you could get it to listen to happen automatically by listening to an npm publish hook. Cheers!
