### ISSUE TITLE
Seq alignment example

### ISSUE THREAD

**Issue by Mokey2002** [TeselaGen/openVectorEditor#712]
@tnrich
Hi,
Is there an specific format I need to enter the sequence for the sequence alignment? On the demo (http://teselagen.github.io/openVectorEditor/#/Editor), when I enter a sequence to align and click create alignment nothing.  Also  is there an example --Im new to this-- that shows how to use the built in alignment creation tool in vanilla javascript? 

-Great app btw

Thanks a lot,
Eduardo

**Comment by tnrich** [comment]
Hey @Mokey2002 

So the alignment tool that has been provided with the demo is hitting a custom alignment route that Teselagen had been hosting for a while now. It looks like that route is no longer maintained (hence the tool not running to completion any more). 

Since OVE is just a visualization library, it doesn't provide any alignment tool out of the box, you'll need to hook it up to your own favorite alignment tool in order to get the actual alignment data yo'd like to visualize. Once you have the alignment data you can pass it to OVE and visualize it either as an MSA or a pairwise alignment depending on the type of alignment you've run. There are examples of how to pass alignment data to the <Alignment/> component in a react context http://teselagen.github.io/openVectorEditor/#/Alignment or outside of it.

**Comment by Mokey2002** [comment]
Got it, thanks!

**Comment by tnrich** [comment]
And, to be clear, I should probably make sure the example route that we provide works 🤭

**Comment by tnrich** [comment]
Closing this as stale
