### ISSUE TITLE
feature type is getting reverted to misc_feature

### ISSUE THREAD

**Issue by ericsturman** [TeselaGen/openVectorEditor#831]
@tnrich

We are noticing new behavior where if a feature type is not listed in `ve-sequence-utils/src/FeatureTypes` it is getting defaulted to `misc_feature`.  Is there a way to override this behavior?

**Comment by tnrich** [comment]
@ericsturman can you provide more info about where this is occurring? In the genbank import of a new file or in the edit feature dialog? 

Also could you do a little digging and see if you can pinpoint which version of OVE this started failing on? 

Hopefully it won't be too hard to track down via https://teselagen.github.io/openVectorEditor/#/Editor using the version chooser here: 
<img width="428" alt="image" src="https://user-images.githubusercontent.com/2730609/173928417-854d2e0f-ade7-48d8-a1c7-672ed4b803d7.png">

Thanks!

**Comment by ericsturman** [comment]
Sorry for the late response @tnrich 

This screenshot shows the desired behavior.  I have modified the `exampleSequenceData.js` to give araC type `stuff` (and color `red`).  in version 16.4.2 it works, but in version 16.4.3 it shows the type as `misc_feature`.
![Screen Shot 2022-06-16 at 11 46 49 AM](https://user-images.githubusercontent.com/4339551/174123803-84872c7b-799f-403a-b2fd-e29c2a37f7cc.png)

Thanks,
Eric

**Comment by tnrich** [comment]
@ericsturman here's the line of code that is creating the change. It is actually something that we wanted in most of our use cases (to prevent non-standard types from being used). I'll try adding a config option, something like `allowNonStandardGenbankTypes` and see if that could work.

**Comment by ericsturman** [comment]
@tnrich That will work.

**Comment by tnrich** [comment]
@ericsturman I've added the following code to ve-sequence-utils: 

<img width="518" alt="image" src="https://user-images.githubusercontent.com/2730609/174387337-b55614fc-c12c-465a-8729-17e2fc082c3c.png">

Basically I added a way to allow OVE implementers to just set `window.tg_allowNonStandardGenbankTypes=true` at their earliest convenience to configure this option. I did this because the tidyUpSequenceData function was getting used in a ton of places (some of them quite nested and inconvenient to pass props to) and because it seems like the kind of option you'll either want for your project or not want (not some in-between). 

So to use it just set `window.tg_allowNonStandardGenbankTypes=true` somewhere early on in the instantiation of your JS code. Let me know if this solves it for you. 

This will land in OVE v17.6.3
